// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrPyiWXBT5j3IQI-bF19AB_bBomEN4Xs',
    appId: '1:474080889408:web:8a59a9500e8870997eeda5',
    messagingSenderId: '474080889408',
    projectId: 'firstapp-max',
    authDomain: 'firstapp-max.firebaseapp.com',
    storageBucket: 'firstapp-max.firebasestorage.app',
    measurementId: 'G-73Z3NC0SMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpCWit5pDhEeYUk5vKNJ6GXNX9N7nAKUY',
    appId: '1:474080889408:android:5783f865105871617eeda5',
    messagingSenderId: '474080889408',
    projectId: 'firstapp-max',
    storageBucket: 'firstapp-max.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKldNcyK5tgJ1BHUabnIR3jbym6_8TXBQ',
    appId: '1:474080889408:ios:c7396daca05d59177eeda5',
    messagingSenderId: '474080889408',
    projectId: 'firstapp-max',
    storageBucket: 'firstapp-max.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
